"""update dialectlist

迁移 ID: fb88e4d27eb8
父迁移: 60daff81fcdc
创建时间: 2025-04-20 11:00:50.931679

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fb88e4d27eb8'
down_revision: str | Sequence[str] | None = '60daff81fcdc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('bot_type', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id1', sa.String(length=64), nullable=False),
    sa.Column('id2', sa.String(length=64), nullable=False),
    sa.Column('id3', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessionmodel')),
    sa.UniqueConstraint('bot_id', 'bot_type', 'platform', 'level', 'id1', 'id2', 'id3', name='unique_session'),
    info={'bind_key': ''}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionmodel')
    # ### end Alembic commands ###
